general {
    lock_cmd = "hyprlock"
    unlock_cmd = "hyprctl dispatch dpms on"
    before_sleep_cmd = "loginctl lock-session"
    after_sleep_cmd = "hyprctl dispatch dpms on"
}

listener {
    timeout = 300
    on_timeout = "hyprlock"
}

listener {
    timeout = 330
    on_timeout = "hyprctl dispatch dpms off"
    on_resume = "hyprctl dispatch dpms on"
}