-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "miku-cursor-linux")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = true,
        inactive_timeout = 0.0,
    },
    decoration = {
        dim_inactive = false,
        fullscreen_opacity = 1.0,
        shadow = {
            offset = "0 0",
        },
    },
    general = {
        gaps_in = 6,
        snap = {
            enabled = false,
        },
    },
    gestures = {
        workspace_swipe_forever = false,
    },
    input = {
        kb_layout = "us,ara",
        kb_options = "grp:alt_shift_toggle",
        numlock_by_default = true,
        touchpad = {
            clickfinger_behavior = true,
            natural_scroll = true,
        },
    },
})

-- Keybinds
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("/home/abo3aisha/.local/bin/open-foot"))
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("/home/abo3aisha/.local/bin/open-foot"))
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("/home/abo3aisha/.local/bin/pick-wallpaper"))
hl.unbind("SUPER + SHIFT + W")
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("/home/abo3aisha/.local/bin/rand-wallpaper"))
hl.unbind("SUPER + ALT + W")
hl.bind("SUPER + ALT + W", hl.dsp.exec_cmd("librewolf"))
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.exec_cmd("/home/abo3aisha/.local/bin/logout-menu"))
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("thunar"))
